name: Linux-Build
on: 
  workflow_dispatch: 
  schedule:
    - cron: "0 22 15 * *"
  push:
    paths:
      - ".github/workflows/linux-build.yml"

jobs: 
  linux-x64-build: 
    runs-on: ubuntu-20.04
    steps: 
      - name: Install dependencies
        shell: bash
        run: |
          sudo apt update &&
          sudo apt upgrade -y &&

          sudo apt install cmake libfmt-dev libssl-dev rapidjson-dev -y

      - name: Clone source
        shell: bash
        run: |
          git clone --depth 1 -b linux --single-branch https://notabug.org/doublesine/navicat-keygen.git

      - name: Build project
        shell: bash
        run: |
          cd navicat-keygen

          mkdir build
          cd build
          cmake -DCMAKE_BUILD_TYPE=Release ..
          cmake --build . -- -j4

          mkdir bin
          mv navicat-keygen navicat-patcher bin
          strip bin/*

      - name: Upload artifacts
        uses: actions/upload-artifact@v3
        with:
          name: linux-x64-build
          path: ${{ GITHUB.WORKSPACE }}/navicat-keygen/build/bin/*
          retention-days: 30
