name: simple-live-build
#推送Tag时触发
on:
  workflow_dispatch:
  push:
    paths:
      - ".github/workflows/simple-live-build.yml"
jobs:
  build-android:
    runs-on: ubuntu-latest
    steps:
      #克隆源代码
      - name: Clone source code
        shell: bash
        run: |
          git clone --single-branch https://github.com/qiunoyi/dart_simple_live.git

      # APK签名设置
      - name: Download Android keystore
        id: android_keystore
        uses: timheuer/base64-to-file@v1.2
        with:
          fileName: keystore.jks
          encodedString: ${{ secrets.KEYSTORE_BASE64 }}

      - name: Create key.properties
        run: |
          echo "storeFile=${{ steps.android_keystore.outputs.filePath }}" > dart_simple_live/simple_live_app/android/key.properties
          echo "storePassword=${{ secrets.STORE_PASSWORD }}" >> dart_simple_live/simple_live_app/android/key.properties
          echo "keyPassword=${{ secrets.KEY_PASSWORD }}" >> dart_simple_live/simple_live_app/android/key.properties
          echo "keyAlias=${{ secrets.KEY_ALIAS }}" >> dart_simple_live/simple_live_app/android/key.properties

      #设置JAVA环境
      - uses: actions/setup-java@v4
        with:
          distribution: "zulu"
          java-version: "17"
          cache: "gradle"

      #设置Flutter
      - name: Flutter action
        uses: subosito/flutter-action@v2
        with:
          flutter-version: "3.35.x"
          cache: true

      #更新Flutter的packages
      - name: Restore packages
        run: |
          cd dart_simple_live/simple_live_app
          flutter pub get

      #打包APK
      - name: Build APK
        run: |
          cd dart_simple_live/simple_live_app
          sed -i '4s/^/#/' android/gradle.properties
          sed -i '81s|^[[:space:]]*//||' android/app/build.gradle
          sed -i '87s|^|//|' android/app/build.gradle
          flutter build apk --release --split-per-abi

      #上传APK至Artifacts
      - name: Upload APK to Artifacts
        uses: actions/upload-artifact@v4
        with:
          name: android
          path: |
            dart_simple_live/simple_live_app/build/app/outputs/flutter-apk/app-arm64-v8a-release.apk

  # 打包Windows
  build-windows:
    runs-on: windows-latest
    steps:
      #克隆源代码
      - name: Clone source code
        shell: cmd
        run: |
          git clone --single-branch https://github.com/qiunoyi/dart_simple_live.git

      # 设置Flutter环境
      - name: Setup Flutter
        uses: subosito/flutter-action@v2
        with:
          flutter-version: "3.35.x"
          cache: true

      - name: Enable Flutter Desktop
        run: flutter config --enable-windows-desktop

      - name: Restore Packages
        run: |
          cd dart_simple_live/simple_live_app
          flutter pub get

      # 设置flutter_distributor环境
      - name: Install flutter_distributor
        run: dart pub global activate flutter_distributor

      # build Windows ZIP
      - name: Build Windows
        run: |
          cd dart_simple_live/simple_live_app
          flutter_distributor package --platform windows --targets zip --skip-clean

      # 上传Windows至Artifacts
      - name: Upload Windows APP to Artifacts
        uses: actions/upload-artifact@v4
        with:
          name: windows
          path: |
            dart_simple_live/simple_live_app/build/dist/*/*.zip
