name: Windows-Build
on: 
  workflow_dispatch: 
  schedule:
    - cron: "0 22 15 * *"
  push:
    paths:
      - ".github/workflows/windows-build.yml"

jobs:
  windows-x64-build: 
    runs-on: windows-latest
    steps:
      - name: Add MSBuild to PATH
        uses: microsoft/setup-msbuild@v1.1.3
        with:
          msbuild-architecture: x64

      - name: Install dependencies
        shell: bash
        run: |
          cd $VCPKG_INSTALLATION_ROOT

          git pull
          vcpkg install openssl:x64-windows-static
          vcpkg install unicorn:x64-windows-static
          vcpkg install fmt:x64-windows-static
          vcpkg install rapidjson:x64-windows-static
          vcpkg install keystone:x64-windows-static
          
          cd -

      - name: Clone source
        shell: bash
        run: |
          git clone -b windows --single-branch https://notabug.org/doublesine/navicat-keygen.git

      - name: Build project
        shell: bash
        run: |
          cd navicat-keygen
          vcpkg integrate install
          
          MSBuild.exe ./navicat-keygen.sln -p:Configuration=Release -p:Platform=x64

          strip bin/x64-Release/*.exe
      
      - name: Upload artifacts
        uses: actions/upload-artifact@v3
        with:
          name: windows-x64-build
          path: ${{ GITHUB.WORKSPACE }}/navicat-keygen/bin/x64-Release/*.exe
          retention-days: 30